### ISSUE TITLE
[Bug] developer login exception

### ISSUE THREAD

**Issue by conorzhao** [apache/streampark#1455] opened 2022-08-26 03:48 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/streamxhub/streamx/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Create a new developer user and exit abnormally immediately after successful login.

### StreamX Version

1.2.4

### Flink Version

1.13.6

### Scala Version of Flink

2.11

### Error Exception

```log
sorry you cant access...
```

### Screenshots

<img width="879" alt="image" src="https://user-images.githubusercontent.com/27194698/186813233-bde476e1-5527-448c-b54d-74456ff6f081.png">

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xujiangfeng001** [comment] 2022-08-29 07:59
Hello, I can't reproduce this bug. Can you tell us your operation steps in detail？

**Comment by conorzhao** [comment] 2022-08-29 08:12
> 

1. First, create a new team

2. Create a developer user and belong to the newly created team

3. Log in with the newly created user

At present, the problem can still recur

**Comment by xujiangfeng001** [comment] 2022-08-29 08:18
Well, thank you very much. I'll have a try.

**Comment by xujiangfeng001** [comment] 2022-08-29 09:15
Hello, I still can't reproduce this bug. Can you confirm whether this PR has been merged?https://github.com/streamxhub/streampark/pull/1346

**Comment by xujiangfeng001** [comment] 2022-08-29 09:16
Hello, I still can't reproduce this bug. Can you confirm whether this PR has been merged?https://github.com/streamxhub/streampark/pull/1346

**Comment by conorzhao** [comment] 2022-08-30 06:58
> 

It looks like the branch is already the latest code, I'm redeploying live

**Comment by conorzhao** [comment] 2022-08-31 09:38
Sorry, the branch code I compiled has not been updated

**Closed as completed** 2022-08-31 09:38 UTC
